import ConnectedPseudospectrum

/-! Kernel-axiom audit for major integrated public theorems. -/

open ConnectedPseudospectrum

#print axioms ConnectedPseudospectrum.mem_spectrum_iff_det_generalShift_eq_zero
#print axioms ConnectedPseudospectrum.generalPseudospectrum_eq_spectrum_union_resolvent
#print axioms ConnectedPseudospectrum.exists_mem_spectrum_mem_pseudospectral_component
#print axioms ConnectedPseudospectrum.contractibleSpace_connectedComponentIn_of_real_mem
#print axioms ConnectedPseudospectrum.isConnected_pseudospectrum_iff_gapBarrier_lt_of_vertical
#print axioms ConnectedPseudospectrum.contractibleSpace_pseudospectral_component_of_vertical
#print axioms ConnectedPseudospectrum.lowerBarrierOrderConstant_mul_tailModel_le_lowerBarrier
#print axioms ConnectedPseudospectrum.lowerBarrier_le_gapBarrier
#print axioms ConnectedPseudospectrum.foldEvenSequence_eq_chebyshevDividedDifference
#print axioms ConnectedPseudospectrum.foldOddSequence_eq_chebyshevDividedDifference
#print axioms ConnectedPseudospectrum.foldEvenSequence_eq_deriv_at_foldXi_collision
#print axioms ConnectedPseudospectrum.foldOddSequence_eq_deriv_at_foldXi_collision
#print axioms ConnectedPseudospectrum.foldEvenSequence_eq_collisionCandidate
#print axioms ConnectedPseudospectrum.foldOddSequence_eq_collisionCandidate
#print axioms ConnectedPseudospectrum.exposedFoldMinorState_extension
#print axioms ConnectedPseudospectrum.foldedEvenActualState_succ
#print axioms ConnectedPseudospectrum.foldedOddActualState_succ
#print axioms ConnectedPseudospectrum.signedPencilDet_even_eq_foldEvenSequence
#print axioms ConnectedPseudospectrum.signedPencilDet_odd_eq_foldOddSequence
#print axioms ConnectedPseudospectrum.continuousOn_foldedHalfVariables_positiveDiscriminant
#print axioms ConnectedPseudospectrum.x_sq_eq_halfChordScale_sq_mul_foldedHalf_sq
#print axioms ConnectedPseudospectrum.s_sq_eq_halfChordScale_sq_mul_foldedHalf_complements
#print axioms ConnectedPseudospectrum.x_eq_halfChordScale_mul_genericHalfVariables
#print axioms ConnectedPseudospectrum.abs_s_eq_halfChordScale_mul_sqrt_genericHalf_complements
#print axioms ConnectedPseudospectrum.leastSingularValue_submatrix_perm
#print axioms ConnectedPseudospectrum.complexPathMatrix_evenOddBlock
#print axioms ConnectedPseudospectrum.complexCentralCompanion_gram_sub_reversed_central_gram
#print axioms ConnectedPseudospectrum.centralBidiagonalHeight_le_companion
#print axioms ConnectedPseudospectrum.leastSingularValue_evenCentralOffDiagonalFin
#print axioms ConnectedPseudospectrum.realGapValue_even_zero_eq_centralBidiagonalHeight
#print axioms ConnectedPseudospectrum.evenCentralInnerLobe_lt_center
#print axioms ConnectedPseudospectrum.centralOuterZ0_radical_eq_height_sq
#print axioms ConnectedPseudospectrum.chordLobeWeight_centralOuterZ0
#print axioms ConnectedPseudospectrum.evenCentralHalfChord_source_formulas
#print axioms
  ConnectedPseudospectrum.EvenCentralHalfGapData.signedPencilDet_selectedRoot_eq_zero_of_mem_gap
#print axioms ConnectedPseudospectrum.EvenCentralHalfGapData.classifiedInGap_eq_univ
#print axioms ConnectedPseudospectrum.EvenCentralHalfGapData.outerLobeMaximizer_le_centralOuterZ0
#print axioms ConnectedPseudospectrum.EvenCentralHalfGapData.chordZ_rightAngle_eq_centralOuterZ0
#print axioms
  EvenCentralHalfGapData.selectedHeight_lt_centralBidiagonalHeight_of_mem_gap
#print axioms ConnectedPseudospectrum.EvenCentralHalfGapData.centralGap_height_eq_and_unique
#print axioms ConnectedPseudospectrum.centralBidiagonal_gram_det
#print axioms ConnectedPseudospectrum.existsUnique_centralRho
#print axioms ConnectedPseudospectrum.centralBidiagonalHeight_sq_eq_rhoLambda
#print axioms ConnectedPseudospectrum.centralRho_identities
#print axioms ConnectedPseudospectrum.hasDerivWithinAt_verticalPencilDet_convolution
#print axioms ConnectedPseudospectrum.vertical_leading_ratio_product
#print axioms ConnectedPseudospectrum.vertical_ratio_cross
#print axioms ConnectedPseudospectrum.hasDerivWithinAt_verticalPencilDet_pos
#print axioms ConnectedPseudospectrum.verticalHeightMonotone
#print axioms ConnectedPseudospectrum.isConnected_pathPseudospectrum_iff_gapBarrier_lt
#print axioms ConnectedPseudospectrum.contractibleSpace_pathPseudospectral_component
#print axioms ConnectedPseudospectrum.foldXiPlus_signed_halfChord
#print axioms ConnectedPseudospectrum.foldEvenSequence_signed_halfChord_eq_zero_iff
#print axioms ConnectedPseudospectrum.foldOddSequence_signed_halfChord_eq_zero_iff
#print axioms ConnectedPseudospectrum.chordLogCurvature_neg
#print axioms ConnectedPseudospectrum.existsUnique_adjacentChordNodeLobeMaximum
#print axioms ConnectedPseudospectrum.existsUnique_outerChordLobeEndpointSolution
#print axioms ConnectedPseudospectrum.signedHalfChord_eq_iff_sign_and_channels
#print axioms ConnectedPseudospectrum.foldEvenSequence_eq_zero_iff_sign_and_channels
#print axioms ConnectedPseudospectrum.foldOddSequence_eq_zero_iff_sign_and_channels
#print axioms ConnectedPseudospectrum.oddSignedMiddleMatrix_central_abs_min_even_gap
#print axioms ConnectedPseudospectrum.oddSignedMiddleMatrix_central_abs_min_odd_gap
#print axioms ConnectedPseudospectrum.evenSignedMiddleMatrix_central_abs_min_even_gap
#print axioms ConnectedPseudospectrum.evenSignedMiddleMatrix_central_abs_min_odd_gap
#print axioms ConnectedPseudospectrum.twoSignedMiddleMatrix_central_abs_min_odd_gap
#print axioms ConnectedPseudospectrum.evenMiddleBranch_bridge_even_gap
#print axioms ConnectedPseudospectrum.evenMiddleBranch_bridge_odd_gap
#print axioms ConnectedPseudospectrum.twoMiddleBranch_bridge_odd_gap
#print axioms ConnectedPseudospectrum.oddMiddleBranch_bridge_even_gap
#print axioms ConnectedPseudospectrum.oddMiddleBranch_bridge_odd_gap
#print axioms ConnectedPseudospectrum.signedPencilPolynomial_eval
#print axioms ConnectedPseudospectrum.signedPencil_endpoint_zero_and_simple
#print axioms ConnectedPseudospectrum.middleBranchExtension_continuousOn_gapClosure
#print axioms ConnectedPseudospectrum.selectedMiddleRoot_eq_negOnePow_mul_height
#print axioms ConnectedPseudospectrum.signedPencilDet_selectedMiddleRoot_eq_zero_of_mem_gap
#print axioms ConnectedPseudospectrum.isOpen_middleBranchRawClassifiedSet
#print axioms ConnectedPseudospectrum.selectedMiddleCoordinates_eq_outerChordFamily_of_agreement
#print axioms ConnectedPseudospectrum.middleBranchClassifiedSet_nonempty
#print axioms ConnectedPseudospectrum.chordLobeWeight_selectedMiddleZ_eq_selectedMiddleY
#print axioms ConnectedPseudospectrum.exists_outerChordFamily_representation_of_classified
#print axioms ConnectedPseudospectrum.selectedMiddleDiscriminant_pos_of_mem_closure
#print axioms ConnectedPseudospectrum.selectedMiddleZ_ne_cosh_of_mem_closure
#print axioms ConnectedPseudospectrum.selectedMiddleZ_ne_outerLobeMaximizer_of_mem_closure
#print axioms ConnectedPseudospectrum.isClosed_middleBranchClassifiedInGap
#print axioms ConnectedPseudospectrum.middleBranchClassifiedInGap_eq_univ
#print axioms ConnectedPseudospectrum.positiveHalfSpectralGap_subset_middleBranchRawClassifiedSet
#print axioms ConnectedPseudospectrum.signedPencilEndpoint_isContDiffImplicitAt
#print axioms ConnectedPseudospectrum.eventually_signedPencilLocalRoot_eq_of_det_zero
#print axioms ConnectedPseudospectrum.eventuallyEq_continuous_signedPencil_root_curves
#print axioms ConnectedPseudospectrum.chordPhi_ratio_gt_noncentralScale
#print axioms ConnectedPseudospectrum.chordPsi_ratio_le_noncentralScale
#print axioms ConnectedPseudospectrum.chordPhi_gt_chordPsi_of_next_eq
#print axioms ConnectedPseudospectrum.existsUnique_rightmostInnerSolution
#print axioms ConnectedPseudospectrum.successorSinhRatio_strictAntiOn_Ioi
#print axioms ConnectedPseudospectrum.hyperbolicOuterCoordinate_preserved
#print axioms ConnectedPseudospectrum.outerChordS_strictMono_innerAngle_hyperbolic
#print axioms ConnectedPseudospectrum.existsUnique_noncentralHyperbolicComparison
#print axioms ConnectedPseudospectrum.existsUnique_rightmostInnerSolutionAtLevel
#print axioms ConnectedPseudospectrum.chordAngleRescaledRatio_strictMonoOn
#print axioms ConnectedPseudospectrum.chordPhi_rescaled_successor_ratio_eq
#print axioms ConnectedPseudospectrum.ellipticOuterCoordinate_preserved
#print axioms ConnectedPseudospectrum.predecessorEllipticLevel_strict
#print axioms ConnectedPseudospectrum.existsUnique_noncentralEllipticComparison
#print axioms ConnectedPseudospectrum.exists_successorOuterChordFamily_representation
#print axioms ConnectedPseudospectrum.successorOuterCoordinate_cases
#print axioms ConnectedPseudospectrum.exists_predecessorChord_strict_of_mem_successorGap
#print axioms ConnectedPseudospectrum.exists_predecessorGapPoint_strict_of_mem_successorGap
#print axioms ConnectedPseudospectrum.complexReflection_mem_unitary
#print axioms ConnectedPseudospectrum.shiftedPathMatrix_neg_ofReal_eq_neg_reflection
#print axioms ConnectedPseudospectrum.pseudospectralHeight_neg_ofReal
#print axioms ConnectedPseudospectrum.realGapValue_neg
#print axioms ConnectedPseudospectrum.reflectedNegativeSpectralGap_eq_Ioo
#print axioms ConnectedPseudospectrum.reflectedNegativeGapIndex_predecessor_successor
#print axioms ConnectedPseudospectrum.exists_predecessorReflectedGapPoint_strict_of_mem_successorGap
#print axioms ConnectedPseudospectrum.OddCentralChordData.positiveGap_angleInterval
#print axioms ConnectedPseudospectrum.OddCentralChordData.positiveHalfSpectralGap_positiveGap
#print axioms ConnectedPseudospectrum.OddCentralChordData.outerChordFamilyX_mem_positiveCentralGap
#print axioms
  ConnectedPseudospectrum.OddCentralChordData.realGapValue_outerChordFamilyX_positiveCentral
#print axioms
  ConnectedPseudospectrum.OddCentralChordData.strictConcaveOn_log_transformedCentralWeight
#print axioms ConnectedPseudospectrum.OddCentralChordData.transformedRho_le_transformedOuter
#print axioms
  ConnectedPseudospectrum.OddCentralChordData.outerChordFamilyS_lt_centralBidiagonalHeight
#print axioms
  OddCentralChordData.realGapValue_lt_centralBidiagonalHeight_of_mem_positiveCentralGap
#print axioms ConnectedPseudospectrum.exists_interior_realGapValue_eq_oddCentralHeight
#print axioms ConnectedPseudospectrum.exists_negative_interior_realGapValue_eq_oddCentralHeight
#print axioms ConnectedPseudospectrum.realGapValue_lt_centralBidiagonalHeight_of_mem_oddCentralGaps
#print axioms ConnectedPseudospectrum.oddCentralHeight_lt_centralBidiagonalHeight
#print axioms ConnectedPseudospectrum.OddCentralChordData.lowerCentralReferenceRho_lt_Rho
#print axioms ConnectedPseudospectrum.OddCentralChordData.lowerCentral_log_drop_strict
#print axioms ConnectedPseudospectrum.OddCentralChordData.lowerCentralSlopeAtRho_eq_of_Rho_eq_one
#print axioms ConnectedPseudospectrum.OddCentralChordData.five_div_reference_den_sq_le_one_fifth
#print axioms ConnectedPseudospectrum.OddCentralChordData.lowerCentralN_pos
#print axioms ConnectedPseudospectrum.OddCentralChordData.lowerCentral_scalar_target
#print axioms ConnectedPseudospectrum.OddCentralChordData.lowerCentral_folded_sum
#print axioms ConnectedPseudospectrum.OddCentralChordData.lowerCentral_folded_product
#print axioms ConnectedPseudospectrum.OddCentralChordData.lowerCentralU_neg_Omega_sq
#print axioms
  ConnectedPseudospectrum.OddCentralChordData.lowerCentralNumerator_difference_product_pos
#print axioms ConnectedPseudospectrum.OddCentralChordData.signedPencilDet_lowerCentral_product_pos
#print axioms ConnectedPseudospectrum.complexPathMatrix_oddCentral_gram_charpoly
#print axioms ConnectedPseudospectrum.complexSignedMiddleMatrix_oddCentral_gram_charpoly
#print axioms ConnectedPseudospectrum.oddCentral_singularSquare_spectrum_certificate
#print axioms ConnectedPseudospectrum.oddCentralSecondSingularValue_le_abs_orderedEigenvalue
#print axioms ConnectedPseudospectrum.exists_orderedSignedMiddleEigenvalue_abs_eq_oddCentralSecond
#print axioms
  ConnectedPseudospectrum.oddCentralSecondSingularValue_is_minimum_positive_abs_eigenvalue
#print axioms ConnectedPseudospectrum.outerChordCharts_join_at_one
#print axioms ConnectedPseudospectrum.outerChordS_factorization
#print axioms ConnectedPseudospectrum.foldXiPlus_signed_outerChord
#print axioms ConnectedPseudospectrum.foldEvenSequence_signed_outerChord_eq_zero_iff
#print axioms ConnectedPseudospectrum.foldOddSequence_signed_outerChord_eq_zero_iff
#print axioms ConnectedPseudospectrum.chordPhi_inner_lt_outerLobeMaximum
#print axioms ConnectedPseudospectrum.outerEndpointSide_foldedVariables_ne
#print axioms ConnectedPseudospectrum.chordLobeWeight_outerChordFamilyZ
#print axioms ConnectedPseudospectrum.continuous_outerChordFamilyZ
#print axioms ConnectedPseudospectrum.outerChordFamily_foldedVariables_ne
#print axioms ConnectedPseudospectrum.outerChordFamilyX_leftAngle
#print axioms ConnectedPseudospectrum.outerChordFamilySignedRoot_rightAngle
#print axioms ConnectedPseudospectrum.outerChordFamily_signed_chord_equation
#print axioms ConnectedPseudospectrum.foldEvenSequence_outerChordFamily_eq_zero
#print axioms ConnectedPseudospectrum.foldOddSequence_outerChordFamily_eq_zero
#print axioms ConnectedPseudospectrum.outerChordFamilyS_pos
#print axioms ConnectedPseudospectrum.outerChordFamilyX_rightAngle_eq_symmetricPathEigenvalue
#print axioms ConnectedPseudospectrum.exists_gapPoint_selectedMiddleAngle_eq
#print axioms ConnectedPseudospectrum.outerChordFamilyX_mem_positiveHalfSpectralGap
#print axioms ConnectedPseudospectrum.outerChordFamilySignedRoot_eq_selectedMiddleRoot
#print axioms ConnectedPseudospectrum.realGapValue_outerChordFamilyX_eq_outerChordFamilyS
#print axioms ConnectedPseudospectrum.signedPencilDet_outerChordFamily_even_eq_zero
#print axioms ConnectedPseudospectrum.signedPencilDet_outerChordFamily_odd_eq_zero
#print axioms
  ConnectedPseudospectrum.signedPencilDet_middleBranchExtension_eq_zero_on_positiveHalfGap
#print axioms ConnectedPseudospectrum.eventually_outerChordFamilyX_mem_spectralGap_left
#print axioms
  ConnectedPseudospectrum.eventually_outerChordFamilySignedRoot_eq_middleBranchExtension_left
#print axioms ConnectedPseudospectrum.outerChordFamily_left_endpoint_germ
#print axioms ConnectedPseudospectrum.chordLobeWeight_strictAntiOn_closedEndpointSide
#print axioms ConnectedPseudospectrum.outerLobeLevelHomeomorph
#print axioms ConnectedPseudospectrum.continuous_outerLobeEndpointSolution
#print axioms ConnectedPseudospectrum.tailThreshold_boundedErrorAtZero
#print axioms ConnectedPseudospectrum.threshold_equality_and_two_sided_bounds
#print axioms ConnectedPseudospectrum.exists_signedPencil_root_abs_eq_pseudospectralHeight
#print axioms ConnectedPseudospectrum.criticalThreshold_hasCriticalSizeAsymptotic
#print axioms ConnectedPseudospectrum.criticalThreshold_eq_two_iff
#print axioms ConnectedPseudospectrum.connectedDimensions_eq_criticalThreshold_tail

/-! Selected exact endpoints supporting the LAA manuscript audit. -/

#print axioms ConnectedPseudospectrum.pathLogParameter_pos
#print axioms ConnectedPseudospectrum.pathParameter_eq_exp_neg_two_mul
#print axioms ConnectedPseudospectrum.pathRate_eq_exp_neg_pathLogParameter
#print axioms ConnectedPseudospectrum.oddLeadingPrincipal_submatrix_eq_evenPathDilation
#print axioms ConnectedPseudospectrum.oddFoldedSignedMiddleMatrix_last_column
#print axioms ConnectedPseudospectrum.oddFoldedSignedMiddleMatrix_last_row
#print axioms ConnectedPseudospectrum.oddFoldedSignedMiddleMatrix_bottom_right
#print axioms ConnectedPseudospectrum.foldRecurrenceSeries_eq_mul_foldQuadraticSeries
#print axioms ConnectedPseudospectrum.det_sub_foldTransfer_eq_foldCharacteristicValue
#print axioms ConnectedPseudospectrum.foldEvenPowerSeries_eq_mul_inv_recurrence
#print axioms ConnectedPseudospectrum.foldOddPowerSeries_eq_mul_inv_recurrence
#print axioms ConnectedPseudospectrum.rectangularPrincipalSine_eq_sine_quotient

/-! Foundational public endpoints used throughout the final assembly. -/

#print axioms ConnectedPseudospectrum.exists_leastSingularVector
#print axioms ConnectedPseudospectrum.leastSingularValue_eq_zero_iff_det_eq_zero
#print axioms ConnectedPseudospectrum.leastSingularValue_mul_le
#print axioms ConnectedPseudospectrum.leastSingularValue_unitary_mul
#print axioms ConnectedPseudospectrum.leastSingularValue_mul_unitary
#print axioms ConnectedPseudospectrum.abs_leastSingularValue_sub_le
#print axioms ConnectedPseudospectrum.continuous_leastSingularValue
#print axioms ConnectedPseudospectrum.exists_realGapValue_eq_gapBarrier
#print axioms
  ConnectedPseudospectrum.generalPseudospectralHeight_isLeast_spectralBackwardErrors
#print axioms ConnectedPseudospectrum.realGapValue_isLeast_spectralBackwardErrors
#print axioms ConnectedPseudospectrum.generalPseudospectrum_affine
#print axioms ConnectedPseudospectrum.generalPseudospectrum_reversal_conjugate
#print axioms
  ConnectedPseudospectrum.positiveToeplitzPseudospectrum_eq_affine_image
#print axioms ConnectedPseudospectrum.positiveToeplitz_corollary
#print axioms ConnectedPseudospectrum.positiveToeplitz_scaled_barrier_succ_lt
#print axioms ConnectedPseudospectrum.positiveToeplitz_scaled_barrier_bounds
#print axioms
  ConnectedPseudospectrum.positiveToeplitz_connectedDimensions_eq_criticalThreshold_tail
#print axioms
  ConnectedPseudospectrum.positiveToeplitz_firstConnectedDimension_isLeast
#print axioms
  ConnectedPseudospectrum.positiveToeplitz_threshold_bounds_and_asymptotic
#print axioms ConnectedPseudospectrum.pathMatrix_eq_gauge_symmetricPath_mul_inv
#print axioms ConnectedPseudospectrum.pathMatrix_mul_reversal
#print axioms ConnectedPseudospectrum.reflection_pathMatrix_reflection
#print axioms ConnectedPseudospectrum.spectrum_pathMatrix
#print axioms ConnectedPseudospectrum.charpoly_pathMatrix_separable
#print axioms ConnectedPseudospectrum.gapBarrier_le_upperBarrier
#print axioms ConnectedPseudospectrum.tendsto_gapBarrier_atTop_zero
#print axioms ConnectedPseudospectrum.gapBarrier_two

/-! The five finite permutation facts are printed directly so that the audit
detects any accidental reintroduction of native reflection or
kernel-bypassing reduction helpers. -/

#print axioms ConnectedPseudospectrum.evenPairedPermutation_one_zero
#print axioms ConnectedPseudospectrum.evenPairedPermutation_one_one
#print axioms ConnectedPseudospectrum.oddPairedPermutation_one_zero
#print axioms ConnectedPseudospectrum.oddPairedPermutation_one_one
#print axioms ConnectedPseudospectrum.oddPairedPermutation_one_two

/-! Weyl isolation, determinant parity, central interlacing, mesh exhaustion,
strict global barrier comparison, and the literal final theorem. -/

#print axioms ConnectedPseudospectrum.abs_orderedSignedMiddleEigenvalue_sub_zero_le
#print axioms ConnectedPseudospectrum.atMostOne_small_orderedSignedMiddleEigenvalue
#print axioms ConnectedPseudospectrum.signedPencilDet_mul_neg_eq_prod_orderedEigenvalue_sq_sub_sq
#print axioms ConnectedPseudospectrum.realGapValue_gt_of_signedPencil_product_pos_of_atMostOne
#print axioms
  ConnectedPseudospectrum.OddCentralChordData.lowerCentralXStar_add_C_lt_mesh_le_secondSingularValue
#print axioms
  ConnectedPseudospectrum.OddCentralChordData.lowerCentral_atMostOne_small_orderedEigenvalue
#print axioms ConnectedPseudospectrum.OddCentralChordData.lowerCentralC_lt_realGapValue_XStar
#print axioms
  ConnectedPseudospectrum.OddCentralChordData.centralBidiagonalHeight_succ_lt_oddCentralHeight
#print axioms ConnectedPseudospectrum.mem_positive_or_reflected_or_central_meshGap
#print axioms ConnectedPseudospectrum.exists_offSpectrum_realGapValue_eq_gapBarrier
#print axioms ConnectedPseudospectrum.gapBarrier_eq_sSup_range_meshGapHeight
#print axioms
  ConnectedPseudospectrum.exists_predecessorPoint_strict_of_mem_successorInterval_offSpectrum
#print axioms ConnectedPseudospectrum.meshGapHeight_succ_lt_gapBarrier
#print axioms ConnectedPseudospectrum.gapBarrier_succ_lt
#print axioms ConnectedPseudospectrum.main_theorem
